name: Deploy to Maven Central

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to deploy in Maven Central (eg: v1.2.3)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_version }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build with Maven
        run: ./mvnw --batch-mode clean install

      - name: Deploy to Maven Central
        run: |
          ./mvnw -Pinternal-release-own-project deploy
          echo 'Now you have to wait for the packages to be published in Maven Central.'
          echo 'You can check it in https://repo.maven.apache.org/maven2/io/archimedesfw/maven/micronaut/micronaut-kotlin-parent/'
